# Generated by Django 3.1.14 on 2022-01-17 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField()),
            ],
        ),
    ]
