# Generated by Django 4.0.1 on 2022-01-22 01:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
